-- ----------------------------------------------------------------------------------------
-- Database Exploration
-- ----------------------------------------------------------------------------------------

-- Explore All Objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES;



-- Explore All Columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers';

-- --------------------------------------------------------------------------------------------------------
-- Dimensions Exploration
-- --------------------------------------------------------------------------------------------------------

-- Explore All countries our customers come from
SELECT DISTINCT country
FROM gold.dim_customers;

-- Explore all categoreis 'The major Divisions'
SELECT DISTINCT category, subcategory, product_name FROM gold.dim_products
ORDER BY 1,2,3;

-- ----------------------------------------------------------------------------------------
-- Date Exploration
-- ----------------------------------------------------------------------------------------

-- Find the date of the first and last order
-- How many years  of sales are available
SELECT 
MIN(order_date) AS first_order_date, 
MAX(order_date) AS last_order_date, 
DATEDIFF(month, MIN(order_date), MAX(order_date)) AS noOfYears
FROM gold.fact_sales;

-- Find the youngest and the oldest customer
SELECT
MIN(birth_date) AS oldest_birthdate,
DATEDIFF(YEAR, MIN(birth_date), GETDATE()) AS oldest_age,
MAX(birth_date) AS youngest_birthdate,
DATEDIFF(YEAR, MAX(birth_date), GETDATE()) AS youngest_age
FROM gold.dim_customers;

-- ----------------------------------------------------------------------------------------
-- Measures Exploration
-- ----------------------------------------------------------------------------------------

-- Find the Total Sales
SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales;

-- Find how many items are sold
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales;

-- Find the average selling price
SELECT AVG(price) AS avg_price FROM gold.fact_sales;

-- Find the Total number of Orders
SELECT COUNT(order_number) AS total_orders FROM gold.fact_sales;
SELECT COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales;
SELECT * FROM gold.fact_sales;

-- Find the Total number of Products
SELECT COUNT(product_key) AS total_products FROM gold.dim_products;
SELECT COUNT(DISTINCT product_key) AS total_products FROM gold.dim_products;

-- Find the total number of customers
SELECT COUNT(customer_key) FROM gold.dim_customers;
SELECT COUNT(DISTINCT customer_key) FROM gold.dim_customers;

-- Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) FROM gold.fact_sales;


-- Generate a Report that shows all key metrics of the business

SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' AS measure_name, AVG(price) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total No. Orders' AS measure_name, COUNT(DISTINCT order_number) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total No. Products' AS measure_name, COUNT(product_name) AS measure_value FROM gold.dim_products
UNION ALL
SELECT 'Total No. Customers' AS measure_name, COUNT(customer_key) AS measure_value FROM gold.dim_customers;


-- ----------------------------------------------------------------------------------------
-- Magnitude Analysis
-- ----------------------------------------------------------------------------------------

-- Find total customers by countries
SELECT
	country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT
	gender,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT
	category,
	COUNT(product_key) total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
	category,
	AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT
	p.category,
	SUM(f.sales_amount)AS total_revenue
FROM gold.dim_products p
JOIN gold.fact_sales f
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

SELECT
	p.category,
	SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Find total revenue that is generated by each customer
SELECT
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
	c.country,
	SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;


-- ----------------------------------------------------------------------------------------
-- Ranking Analysis
-- ----------------------------------------------------------------------------------------

-- Which 5 products generate the highest revenue
SELECT *
FROM
	(SELECT
		p.product_name,
		SUM(f.sales_amount) as total_revenue,
		ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) DESC) AS ranking
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_products p
	ON p.product_key = f.product_key
	GROUP BY p.product_name)t
WHERE ranking <= 5;

----- Or ------

SELECT TOP 5
	p.product_name,
	SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;

-- What are the 5 worst- performing products in terms of sales?

SELECT TOP 5
	p.product_name,
	SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC;

-- Top 10 Customers that had generated the highest revenue
SELECT *
FROM
	(SELECT
		f.customer_key,
		c.first_name,
		c.last_name,
		SUM(f.sales_amount) AS total_revenue,
		ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) DESC) AS ranking
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_customers c
	ON c.customer_key = f.customer_key
	GROUP BY f.customer_key, c.first_name, c.last_name)t
WHERE ranking <= 10;

-- 3 Customers with fewest orders placed

SELECT TOP 3
	f.customer_key,
	c.first_name,
	c.last_name,
	COUNT(DISTINCT f.order_number) AS noOrders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY f.customer_key,c.first_name,c.last_name
ORDER BY noOrders;

